version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "13:00"
      timezone: "Europe/Berlin"
    target-branch: "develop"

