name: org-parent-release-workflow
run-name: Release run ${{ github.run_number }}
on: 
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jre'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Build & Test
        run: mvn --batch-mode -U clean package
      - name: Deploy to GitHub
        run: echo "Deployment not setup yet."
